# This will run tests and validate that the code is up to snuff
name: CI

# Trigger the workflow on push or pull request.
on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [synchronize, opened, reopened]

env:
  flutter_version: 3.24.0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-path: /opt/hostedtoolcache/flutter
          cache-key: flutter-${{ env.flutter_version }}
          flutter-version: ${{ env.flutter_version }}
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-fatal-infos
      - name: Format
        run: dart format --set-exit-if-changed -o none .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-path: /opt/hostedtoolcache/flutter
          cache-key: flutter-${{ env.flutter_version }}
          flutter-version: ${{ env.flutter_version }}
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Tests
        run: flutter test --coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          name: flutter-command-palette-coverage
