name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  # publish:
  #   name: Publish Release to Pub.dev
  #   uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
  #   with:
  #     environment: pub.dev

  release:
    name: Create Release on GH
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
